apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mirth-connect
  labels:
    app: mirth-connect
  name: db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
